"""
Build ``data/gallery/catalog.json`` — the topic catalogue behind the Gallery.

Two tiers of entry:

* ``status: "outline"`` — a curated topic with a real, structured teaching
  brief. ``gallery.builder`` runs each of these through the pipeline to produce
  a finished, browsable deck.
* ``status: "index"`` — a browsable title + subject + tags only. Shown in the
  Gallery so the catalogue spans 1000+ topics; opening one drops the user on
  Create pre-filled, rather than showing a pre-built deck.

Run:  PYTHONPATH=src .venv/bin/python scripts/gallery/build_catalog.py
"""

from __future__ import annotations

import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "data" / "gallery" / "catalog.json"


def slugify(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return s[:80]


# ─────────────────────────────────────────────────────────────────────────────
# Curated topics — each carries a real structured brief the pipeline can teach.
# Keep briefs 120–260 words, with ## headings, an ordered list and a bullet
# list, so the layout engine has genuine structure to reason over.
# ─────────────────────────────────────────────────────────────────────────────

def brief(defn: str, ideas: list[str], steps: list[str], example: str,
          pitfalls: list[str], summary: str, matters: str = "", terms: list | None = None) -> str:
    """A structured teaching brief → ~8 slides. The web deck reveals each
    numbered step and bullet one click at a time."""
    parts: list[str] = [defn.strip(), ""]
    if matters:
        parts += ["## Why it matters", matters.strip(), ""]
    if terms:
        parts += ["## Key terms", *[f"- {t}" for t in terms], ""]
    parts += [
        "## The core ideas",
        *[f"- {i}" for i in ideas],
        "",
        "## How it works, step by step",
        *[f"{n}. {s}" for n, s in enumerate(steps, 1)],
        "",
        "## A worked example",
        example.strip(),
        "",
        "## Where people go wrong",
        *[f"- {p}" for p in pitfalls],
        "",
        "## The takeaway",
        summary.strip(),
    ]
    return "\n".join(parts)


CURATED: list[dict] = [
    # ── Biology ──────────────────────────────────────────────────────────────
    dict(
        title="Photosynthesis", subject="Biology", category="Science",
        tags=["cells", "energy", "plants", "chemistry"], level="Introductory", minutes=7,
        outline="## Photosynthesis\n\nPhotosynthesis is the process by which plants, algae and some bacteria convert light energy into chemical energy stored as glucose, releasing oxygen as a by-product.\n\n"
        + brief(
            "The overall reaction takes carbon dioxide and water and, using light captured by chlorophyll, builds glucose and oxygen.",
            ["Light-dependent reactions run in the thylakoid membranes and produce ATP and NADPH",
             "The Calvin cycle runs in the stroma and fixes CO2 into sugar using that ATP and NADPH",
             "Chlorophyll absorbs red and blue light strongly and reflects green",
             "Only about 1–2% of incoming solar energy is captured as chemical energy"],
            ["Light strikes photosystem II and excites electrons, splitting water and releasing O2",
             "Electrons pass down an electron transport chain, pumping protons to drive ATP synthase",
             "Photosystem I re-energises the electrons to reduce NADP+ to NADPH",
             "In the Calvin cycle, RuBisCO fixes CO2 onto RuBP; ATP and NADPH reduce it to G3P",
             "Some G3P leaves to form glucose; the rest regenerates RuBP"],
            "A leaf in bright noon sun fixes CO2 quickly, but on a hot dry afternoon its stomata close to save water. CO2 inside the leaf falls, RuBisCO starts binding O2 instead (photorespiration) and the net sugar gain drops.",
            ["Confusing the light reactions (make ATP/NADPH) with the Calvin cycle (uses them)",
             "Thinking the Calvin cycle does not need light — it needs the products of the light reactions",
             "Assuming plants only respire at night; they respire continuously"],
            "Photosynthesis turns light, water and CO2 into sugar and oxygen in two linked stages: energy capture, then carbon fixation.",
            matters='Almost every food chain on Earth starts here, and photosynthesis is what keeps atmospheric oxygen and carbon dioxide in balance.',
        ),
    ),
    dict(
        title="DNA Replication", subject="Biology", category="Science",
        tags=["genetics", "molecular biology", "cell cycle"], level="Intermediate", minutes=8,
        outline="## DNA Replication\n\nDNA replication is the semi-conservative process that copies a cell's genome before division, so each daughter cell receives an identical set of instructions.\n\n"
        + brief(
            "Each strand of the double helix serves as a template for a new complementary strand, producing two helices that each keep one old strand.",
            ["Replication is semi-conservative — proven by the Meselson–Stahl experiment",
             "It starts at defined origins and proceeds in both directions",
             "DNA polymerase only adds nucleotides 5' to 3', so one strand is made continuously and one in fragments",
             "Proofreading by polymerase keeps the error rate near 1 in 10^9 bases"],
            ["Helicase unwinds the double helix at the origin, forming a replication fork",
             "Single-strand binding proteins hold the strands apart; topoisomerase relieves supercoiling ahead",
             "Primase lays down a short RNA primer",
             "DNA polymerase III extends the leading strand continuously and the lagging strand as Okazaki fragments",
             "DNA polymerase I replaces primers with DNA; ligase seals the nicks"],
            "On the lagging strand, primase must repeatedly re-prime as the fork opens. Each Okazaki fragment is roughly 100–200 bases in eukaryotes, later stitched together by ligase into one continuous strand.",
            ["Saying both strands are synthesised continuously",
             "Forgetting that primers are RNA, not DNA",
             "Confusing helicase (unwinds) with polymerase (builds)"],
            "Replication unzips the helix and builds a matching partner for each strand, one continuously and one in pieces.",
            matters='Every time a cell divides it must copy three billion base pairs almost perfectly; the same machinery is the target of many cancer drugs and antibiotics.',
        ),
    ),
    dict(
        title="Natural Selection", subject="Biology", category="Science",
        tags=["evolution", "Darwin", "genetics", "adaptation"], level="Introductory", minutes=6,
        outline="## Natural Selection\n\nNatural selection is the process by which heritable traits that improve survival and reproduction become more common in a population over generations.\n\n"
        + brief(
            "Given variation, heredity and differential reproductive success, allele frequencies shift toward traits that fit the current environment.",
            ["Individuals vary, and some of that variation is heritable",
             "More offspring are produced than the environment can support",
             "Traits that raise reproductive success spread; the process has no goal or foresight",
             "Selection acts on phenotypes but changes are recorded in allele frequencies"],
            ["A population shows heritable variation in a trait",
             "The environment imposes a challenge — a predator, a drought, a new food source",
             "Individuals with favourable variants survive and reproduce at higher rates",
             "Their alleles are over-represented in the next generation",
             "Over many generations the population's trait distribution shifts"],
            "On the Galápagos, a dry year leaves only large, hard seeds. Finches with deeper beaks crack them and survive; the next generation's average beak depth measurably increases — then partly reverses in a wet year.",
            ["Thinking individuals evolve — populations do",
             "Assuming selection produces perfect or 'advanced' organisms",
             "Confusing natural selection (a mechanism) with evolution (the outcome)"],
            "Natural selection is heredity plus variation plus differential survival, compounding over generations.",
            matters='It explains the fit between living things and their environment without appealing to design, and it is why antibiotic and pesticide resistance evolve.',
        ),
    ),
    # ── Chemistry ────────────────────────────────────────────────────────────
    dict(
        title="The Periodic Table", subject="Chemistry", category="Science",
        tags=["elements", "atomic structure", "trends"], level="Introductory", minutes=6,
        outline="## The Periodic Table\n\nThe periodic table arranges the elements by increasing atomic number so that elements with similar chemical behaviour fall into the same column.\n\n"
        + brief(
            "Position predicts properties: reactivity, atomic radius, ionisation energy and typical charges all follow from where an element sits.",
            ["Rows are periods; columns are groups sharing a valence electron count",
             "Metals sit left and centre, non-metals top right, metalloids on the staircase",
             "Atomic radius decreases across a period and increases down a group",
             "Ionisation energy and electronegativity increase across and up"],
            ["Read the atomic number to get the proton count and electron count of the neutral atom",
             "Fill electron shells to find the valence electrons",
             "Use the group to predict the common ion charge",
             "Use period and group position to rank radius and ionisation energy",
             "Predict bonding: metal + non-metal tends ionic, non-metal + non-metal tends covalent"],
            "Sodium (group 1) has one valence electron it loses easily, giving Na+. Chlorine (group 17) needs one, giving Cl-. They form the ionic solid NaCl, whereas two chlorine atoms share a pair to form covalent Cl2.",
            ["Reading group numbers off an old table with different conventions",
             "Assuming radius grows with atomic number in a straight line",
             "Forgetting that transition metals can show several oxidation states"],
            "The table is a map: an element's row and column tell you how it will react.",
            matters='It lets you predict how an unfamiliar element behaves from its position alone, which is the starting point for all of chemistry.',
        ),
    ),
    dict(
        title="Acids, Bases and pH", subject="Chemistry", category="Science",
        tags=["equilibrium", "titration", "pH", "reactions"], level="Intermediate", minutes=7,
        outline="## Acids, Bases and pH\n\npH measures the concentration of hydrogen ions in a solution on a logarithmic scale, capturing how acidic or basic that solution is.\n\n"
        + brief(
            "Acids donate protons and bases accept them; pH = -log[H+], so each unit is a tenfold change in acidity.",
            ["Pure water is neutral at pH 7 (25 °C) with [H+] = [OH-] = 1e-7 M",
             "Strong acids and bases dissociate fully; weak ones reach an equilibrium",
             "A buffer resists pH change by pairing a weak acid with its conjugate base",
             "pH + pOH = 14 at 25 °C"],
            ["Identify whether the acid or base is strong or weak",
             "For strong species, [H+] or [OH-] equals the concentration",
             "For weak species, set up the Ka or Kb equilibrium expression",
             "Solve for [H+], then take -log to get pH",
             "For a buffer, apply the Henderson–Hasselbalch equation"],
            "0.1 M HCl is a strong acid, so [H+] = 0.1 M and pH = 1. But 0.1 M acetic acid (Ka = 1.8e-5) only partly dissociates: [H+] ≈ 1.3e-3 M, giving pH ≈ 2.9 — far less acidic at the same concentration.",
            ["Treating weak acids as if they fully dissociate",
             "Forgetting pH is logarithmic — pH 3 is 100× more acidic than pH 5",
             "Assuming a neutral solution is always pH 7 regardless of temperature"],
            "pH is a log scale of proton concentration; strong species dissociate fully, weak ones sit at equilibrium.",
            matters='Blood, soil, oceans, medicines and food all depend on pH staying in a narrow range, and one unit is a tenfold change in acidity.',
        ),
    ),
    # ── Physics ──────────────────────────────────────────────────────────────
    dict(
        title="Newton's Laws of Motion", subject="Physics", category="Science",
        tags=["mechanics", "forces", "dynamics"], level="Introductory", minutes=7,
        outline="## Newton's Laws of Motion\n\nNewton's three laws relate the forces on an object to its motion, forming the foundation of classical mechanics.\n\n"
        + brief(
            "An object's acceleration is set by the net force on it and its mass; forces always come in equal and opposite pairs.",
            ["First law: with zero net force, velocity stays constant (inertia)",
             "Second law: F_net = m·a, a vector equation",
             "Third law: every force has an equal and opposite reaction on a different body",
             "Weight is a force (m·g); mass is the amount of matter"],
            ["Draw a free-body diagram showing every force on the object",
             "Choose axes and resolve forces into components",
             "Sum the forces along each axis to get the net force",
             "Apply F_net = m·a along each axis",
             "Solve for the unknown — acceleration, tension, friction or normal force"],
            "A 2 kg book sits on a table. Gravity pulls down with 19.6 N; the table pushes up with 19.6 N. Net force is zero, so by the first law the book stays at rest. Push it with 5 N against 3 N of friction and it accelerates at (5−3)/2 = 1 m/s².",
            ["Thinking a moving object needs a continuous force to keep moving",
             "Pairing the wrong forces as 'action–reaction' (they act on different bodies)",
             "Confusing mass and weight"],
            "Net force equals mass times acceleration; no net force means no change in motion.",
            matters='They predict the motion of everything from a thrown ball to a spacecraft, and every later mechanics course builds on them.',
        ),
    ),
    dict(
        title="Electric Circuits", subject="Physics", category="Science",
        tags=["electricity", "Ohm's law", "current", "voltage"], level="Introductory", minutes=6,
        outline="## Electric Circuits\n\nAn electric circuit is a closed loop through which charge flows, driven by a voltage source and limited by the circuit's resistance.\n\n"
        + brief(
            "Ohm's law (V = I·R) ties voltage, current and resistance; series and parallel arrangements combine components in predictable ways.",
            ["Current is the same everywhere in a series loop; voltage splits across components",
             "Voltage is the same across parallel branches; current splits between them",
             "Resistances add in series; reciprocals add in parallel",
             "Power dissipated is P = V·I = I²·R"],
            ["Identify the source voltage and every resistor",
             "Combine series and parallel resistors into one equivalent resistance",
             "Use V = I·R to find the total current from the source",
             "Work backwards to find the voltage across and current through each component",
             "Check with Kirchhoff's laws: currents into a node sum to zero, voltages around a loop sum to zero"],
            "A 12 V battery drives two 6 Ω resistors in series. Total R = 12 Ω, so I = 1 A everywhere. Each resistor drops 6 V. Put the same two in parallel and R = 3 Ω, I_total = 4 A, with 2 A in each branch.",
            ["Assuming current is 'used up' as it goes around the loop",
             "Adding parallel resistances directly instead of reciprocals",
             "Mixing up which quantity stays constant in series vs parallel"],
            "Voltage pushes, resistance limits, current flows; series shares current, parallel shares voltage.",
            matters='Every device you use is a circuit, and understanding series and parallel behaviour is what lets you design, debug or stay safe around one.',
        ),
    ),
    # ── Mathematics ──────────────────────────────────────────────────────────
    dict(
        title="Derivatives and the Chain Rule", subject="Mathematics", category="Math",
        tags=["calculus", "differentiation", "rates of change"], level="Intermediate", minutes=8,
        outline="## Derivatives and the Chain Rule\n\nThe derivative measures the instantaneous rate of change of a function; the chain rule differentiates compositions of functions.\n\n"
        + brief(
            "If y depends on u and u depends on x, then dy/dx = dy/du · du/dx — rates of change multiply along the chain.",
            ["The derivative is the slope of the tangent line, the limit of the difference quotient",
             "Power, product and quotient rules cover most elementary combinations",
             "The chain rule handles 'a function inside a function'",
             "Differentiability implies continuity, but not the reverse"],
            ["Identify the outer function and the inner function",
             "Differentiate the outer function, leaving the inner one untouched",
             "Multiply by the derivative of the inner function",
             "Simplify, and substitute back if you introduced a helper variable",
             "Check units or limiting behaviour for a sanity test"],
            "Differentiate y = (3x² + 1)⁵. Outer: u⁵ → 5u⁴. Inner: 3x² + 1 → 6x. So dy/dx = 5(3x² + 1)⁴ · 6x = 30x(3x² + 1)⁴.",
            ["Forgetting to multiply by the derivative of the inside",
             "Applying the power rule to the whole expression as if the inside were just x",
             "Confusing the chain rule with the product rule"],
            "To differentiate a composition, differentiate the outside, keep the inside, then multiply by the inside's derivative.",
            matters='Rates of change appear everywhere, and the chain rule is the tool that makes almost every real-world derivative computable.',
        ),
    ),
    dict(
        title="Bayes' Theorem", subject="Mathematics", category="Math",
        tags=["probability", "statistics", "inference"], level="Intermediate", minutes=7,
        outline="## Bayes' Theorem\n\nBayes' theorem updates the probability of a hypothesis in light of new evidence, combining a prior belief with the likelihood of what was observed.\n\n"
        + brief(
            "P(H|E) = P(E|H)·P(H) / P(E): the posterior is the prior times the likelihood, normalised.",
            ["The prior P(H) is your belief before seeing the evidence",
             "The likelihood P(E|H) is how expected the evidence is if H is true",
             "The base rate dominates when the evidence is weak or the condition is rare",
             "Rare conditions make even accurate tests produce many false positives"],
            ["Write down the prior probability of the hypothesis",
             "Write the likelihood of the evidence under the hypothesis and under its negation",
             "Compute the total probability of the evidence P(E)",
             "Divide to get the posterior P(H|E)",
             "Iterate: today's posterior becomes tomorrow's prior"],
            "A disease affects 1 in 1000 people. A test is 99% accurate both ways. You test positive. P(disease | positive) = (0.99 · 0.001) / (0.99 · 0.001 + 0.01 · 0.999) ≈ 0.09 — only about 9%, because healthy false positives vastly outnumber true cases.",
            ["Ignoring the base rate and reading test accuracy as the answer",
             "Swapping P(E|H) and P(H|E)",
             "Forgetting to include the false-positive path in P(E)"],
            "Bayes' theorem rescales your prior by how well the hypothesis predicted the evidence.",
            matters='It is how you should update beliefs from evidence, and ignoring it is why people badly misjudge medical tests and rare-event risks.',
        ),
    ),
    # ── Computer Science ─────────────────────────────────────────────────────
    dict(
        title="Big-O Notation", subject="Computer Science", category="Technology",
        tags=["algorithms", "complexity", "performance"], level="Introductory", minutes=6,
        outline="## Big-O Notation\n\nBig-O notation describes how an algorithm's running time or memory grows as the input size grows, ignoring constants and lower-order terms.\n\n"
        + brief(
            "It captures the dominant term of the cost function, so O(2n + 5) is just O(n) and O(3n² + n) is O(n²).",
            ["It is an upper bound on growth, not an exact running time",
             "Common classes: O(1), O(log n), O(n), O(n log n), O(n²), O(2ⁿ)",
             "Constants and machine speed do not change the class",
             "Best, average and worst cases can differ (quicksort: O(n log n) vs O(n²))"],
            ["Count the operations as a function of input size n",
             "Drop constant factors and additive constants",
             "Keep only the fastest-growing term",
             "Name the class and note whether it is best, average or worst case",
             "Compare against alternatives at large n, not small n"],
            "A nested loop over an array of length n does about n·n = n² comparisons — O(n²). Adding a single pass afterward gives n² + n operations, still O(n²) because n² dominates as n grows.",
            ["Reporting O(n² + n) instead of O(n²)",
             "Assuming a lower Big-O always wins for small inputs",
             "Confusing time complexity with actual wall-clock time"],
            "Big-O names the shape of the growth curve, not the exact cost.",
            matters='It tells you whether a program will still work when the data gets 100 times bigger, which is the difference between a prototype and a product.',
        ),
    ),
    dict(
        title="How HTTPS Works", subject="Computer Science", category="Technology",
        tags=["networking", "security", "TLS", "encryption"], level="Intermediate", minutes=7,
        outline="## How HTTPS Works\n\nHTTPS is HTTP carried over a TLS connection, which authenticates the server and encrypts everything exchanged between browser and site.\n\n"
        + brief(
            "A TLS handshake uses asymmetric cryptography to agree a shared secret, then switches to fast symmetric encryption for the session.",
            ["The certificate proves the server owns the domain, signed by a trusted CA",
             "Asymmetric keys set up the connection; symmetric keys carry the data",
             "Modern TLS uses ephemeral keys so past traffic stays safe if a key leaks (forward secrecy)",
             "The browser verifies the certificate chain up to a root it trusts"],
            ["The client sends a hello with supported cipher suites and a random value",
             "The server replies with its certificate and its own random value",
             "The client verifies the certificate chain and expiry",
             "Both sides derive the same session keys via a key-exchange algorithm",
             "All further HTTP messages are encrypted and integrity-protected with those keys"],
            "You open a bank site. The browser checks the certificate names match the domain and chains to a trusted root. A Diffie–Hellman exchange produces a shared key neither an eavesdropper nor a future attacker with the server's private key can recover.",
            ["Thinking HTTPS hides which site you visited (the domain is often still visible)",
             "Believing a padlock means the site is trustworthy, only that the channel is encrypted",
             "Confusing hashing with encryption"],
            "HTTPS authenticates the server with a certificate, then encrypts the session with a freshly negotiated shared key.",
            matters='It is what makes online banking, logins and private messaging possible, and it tells you exactly what a padlock does and does not promise.',
        ),
    ),
    # ── History ──────────────────────────────────────────────────────────────
    dict(
        title="The Industrial Revolution", subject="History", category="Humanities",
        tags=["18th century", "economics", "technology", "Britain"], level="Introductory", minutes=8,
        outline="## The Industrial Revolution\n\nThe Industrial Revolution was the shift, beginning in Britain around 1760, from hand production and agriculture to machine manufacturing, factories and steam power.\n\n"
        + brief(
            "New energy sources, mechanised textile production and the factory system multiplied output and reshaped where and how people lived.",
            ["Steam power freed factories from rivers and multiplied available energy",
             "Textiles led: the spinning jenny, water frame and power loom",
             "Urban populations exploded as workers moved to factory towns",
             "Railways collapsed travel times and knit markets together"],
            ["Agricultural improvements raised food output and freed labour",
             "Coal and iron industries expanded to feed machinery and rails",
             "Textile inventions moved spinning and weaving into powered mills",
             "The factory system concentrated workers, capital and machines under one roof",
             "Railways and steamships spread the model across Europe and North America"],
            "In 1750 a handloom weaver in a cottage might produce a few metres of cloth a day. By 1850 a single Lancashire mill worker tending powered looms produced many times that — at a fraction of the cost, but on the mill's schedule, not their own.",
            ["Treating it as a single sudden event rather than a decades-long process",
             "Ignoring the social costs: child labour, pollution, unsafe factories",
             "Assuming every country industrialised the same way or at the same time"],
            "Machines, coal and the factory turned scarce, slow handcraft into cheap mass production — and moved life into the city.",
            matters='It created the modern world: cities, factories, wage labour, mass production and the fossil-fuel economy we still live with.',
        ),
    ),
    dict(
        title="The Cold War", subject="History", category="Humanities",
        tags=["20th century", "USA", "USSR", "geopolitics"], level="Intermediate", minutes=9,
        outline="## The Cold War\n\nThe Cold War was the decades-long geopolitical rivalry (roughly 1947–1991) between the United States and the Soviet Union, fought through proxy wars, alliances, propaganda and an arms race rather than direct combat.\n\n"
        + brief(
            "Two superpowers with opposed ideologies and nuclear arsenals competed for global influence while avoiding direct war under the logic of mutual deterrence.",
            ["Ideological split: liberal capitalism versus state socialism",
             "Nuclear weapons made direct war unthinkable — 'mutually assured destruction'",
             "Competition ran through proxies: Korea, Vietnam, Afghanistan, Latin America",
             "Alliances hardened into NATO and the Warsaw Pact"],
            ["Post-war Europe divides; the Iron Curtain falls across the continent",
             "The Truman Doctrine and Marshall Plan commit the US to containment",
             "Crises peak — the Berlin blockade, Cuba 1962 — then pull back from the brink",
             "Détente in the 1970s eases tensions with arms-control treaties",
             "Soviet economic stagnation and reform under Gorbachev end with the USSR's collapse in 1991"],
            "In October 1962 US reconnaissance found Soviet nuclear missiles in Cuba. Thirteen days of brinkmanship ended with a secret deal: the USSR withdrew the missiles, the US pledged not to invade Cuba and quietly removed missiles from Turkey.",
            ["Picturing it as constant crisis — long stretches were stable stalemate",
             "Treating every regional conflict as purely a superpower puppet show",
             "Assuming the outcome was inevitable"],
            "Two nuclear superpowers competed everywhere except the battlefield, until one side's system gave out.",
            matters='It shaped nearly every border, alliance and proxy conflict of the late twentieth century, and its nuclear standoff still exists.',
        ),
    ),
    # ── Economics & Business ─────────────────────────────────────────────────
    dict(
        title="Supply and Demand", subject="Economics", category="Business",
        tags=["microeconomics", "markets", "price", "equilibrium"], level="Introductory", minutes=6,
        outline="## Supply and Demand\n\nSupply and demand is the model of how prices and quantities are set in a competitive market by the interaction of buyers and sellers.\n\n"
        + brief(
            "The market clears where the quantity buyers want equals the quantity sellers offer; shifts in either curve move that equilibrium.",
            ["Demand slopes down: lower price, more wanted",
             "Supply slopes up: higher price, more produced",
             "Equilibrium is the price where the two quantities match",
             "A change in price moves along a curve; a change in anything else shifts the whole curve"],
            ["Draw demand and supply on price–quantity axes",
             "Find the intersection: the equilibrium price and quantity",
             "Identify the shock — a change in income, input costs, tastes or expectations",
             "Shift the relevant curve and read off the new equilibrium",
             "State the direction of change in both price and quantity"],
            "A frost destroys half the coffee crop. Supply shifts left. At the old price there is now a shortage, so price rises and quantity falls until buyers and remaining sellers agree again — a higher price, a smaller quantity.",
            ["Confusing a shift of a curve with a movement along it",
             "Shifting demand when the real cause was a price change",
             "Assuming price controls make shortages or surpluses disappear"],
            "Price settles where quantity demanded meets quantity supplied; outside shocks shift a curve and move that point.",
            matters='It is the most useful model in economics: it explains prices, shortages, surpluses and why price controls often backfire.',
        ),
    ),
    dict(
        title="Compound Interest", subject="Finance", category="Business",
        tags=["investing", "time value of money", "growth"], level="Introductory", minutes=5,
        outline="## Compound Interest\n\nCompound interest is interest earned on both the original principal and the interest already accumulated, so a balance grows faster over time.\n\n"
        + brief(
            "Future value = P·(1 + r/n)^(n·t): compounding more often and waiting longer both increase the result, but time matters most.",
            ["Simple interest grows linearly; compound interest grows exponentially",
             "The rule of 72: divide 72 by the percent rate to estimate the doubling time",
             "More frequent compounding helps, with diminishing returns toward continuous compounding",
             "Inflation compounds too, so compare real (after-inflation) returns"],
            ["Identify the principal, the annual rate, the compounding frequency and the time",
             "Convert the rate per period: r/n",
             "Raise (1 + r/n) to the number of periods n·t",
             "Multiply by the principal to get the future value",
             "Subtract the principal to isolate the interest earned"],
            "£1,000 at 6% compounded annually becomes £1,000·(1.06)^30 ≈ £5,743 after 30 years. At simple interest it would be only £1,000 + 30·£60 = £2,800. The extra £2,943 is interest on interest.",
            ["Using the annual rate without dividing by the number of periods",
             "Underestimating how much the last decade contributes",
             "Ignoring fees and inflation, which compound against you"],
            "Compounding pays interest on your interest, so starting early beats saving more later.",
            matters='It is why starting to save at 25 beats saving twice as much at 45, and why credit-card debt grows so fast.',
        ),
    ),
    # ── Psychology ───────────────────────────────────────────────────────────
    dict(
        title="Classical and Operant Conditioning", subject="Psychology", category="Social Science",
        tags=["learning", "behaviourism", "Pavlov", "Skinner"], level="Introductory", minutes=6,
        outline="## Classical and Operant Conditioning\n\nConditioning is learning through association: classical conditioning links two stimuli, while operant conditioning links a behaviour to its consequence.\n\n"
        + brief(
            "Classical conditioning is about what precedes a reflex; operant conditioning is about what follows a voluntary action.",
            ["Classical: a neutral stimulus paired with a meaningful one comes to trigger the response",
             "Operant: reinforcement increases a behaviour, punishment decreases it",
             "Reinforcement and punishment can each be positive (add) or negative (remove)",
             "Intermittent reinforcement produces behaviour that is hard to extinguish"],
            ["Decide whether the behaviour is a reflex (classical) or a chosen action (operant)",
             "For classical, name the unconditioned stimulus, response, and the neutral stimulus being paired",
             "For operant, name the behaviour and its consequence",
             "Classify the consequence: positive/negative, reinforcement/punishment",
             "Predict the change in behaviour frequency over repeated trials"],
            "A dog hears a bell before every meal and starts salivating at the bell alone — classical. Later it learns that pressing a lever produces a treat and presses more often — operant, positive reinforcement.",
            ["Calling negative reinforcement a punishment — it removes something unpleasant to increase behaviour",
             "Assuming punishment teaches the right behaviour rather than just suppressing one",
             "Mixing up which type applies to reflexes versus choices"],
            "Classical conditioning trains a trigger; operant conditioning trains a habit through its consequences.",
            matters='These two mechanisms explain phobias, habits, advertising and training from a handful of simple rules.',
        ),
    ),
    # ── Earth & Environment ──────────────────────────────────────────────────
    dict(
        title="The Carbon Cycle", subject="Environmental Science", category="Science",
        tags=["climate", "ecology", "biogeochemistry"], level="Introductory", minutes=7,
        outline="## The Carbon Cycle\n\nThe carbon cycle is the continuous movement of carbon between the atmosphere, oceans, living things, soils and rocks.\n\n"
        + brief(
            "Carbon flows fast between air, life and surface ocean, and slowly into rock and fossil deposits; burning fossil fuels short-circuits the slow path into the fast one.",
            ["Photosynthesis removes CO2 from the air; respiration and decay return it",
             "The ocean holds far more carbon than the atmosphere and exchanges it at the surface",
             "The slow cycle locks carbon in limestone and fossil fuels for millions of years",
             "Human emissions add roughly 10 billion tonnes of carbon a year to the fast cycle"],
            ["Plants and plankton fix atmospheric CO2 into organic carbon",
             "Animals eat plants; respiration returns some carbon to the air",
             "Dead matter decomposes, releasing CO2 or forming soil carbon",
             "Over geological time, buried carbon becomes rock, coal, oil and gas",
             "Weathering and volcanism slowly return that carbon to the surface"],
            "A carbon atom in a 2024 breath of CO2 might be absorbed by a tree next spring, released when a leaf decays two years later, dissolve into the ocean, and only after millennia settle into seafloor sediment.",
            ["Treating the atmosphere as the largest carbon store — the oceans and rocks hold much more",
             "Ignoring the timescale difference between the fast and slow cycles",
             "Assuming forests can absorb all human emissions"],
            "Carbon shuttles quickly among air, life and ocean, and slowly into rock — and we are moving buried carbon back up fast.",
            matters='Understanding it is what lets you see why burning fossil fuels changes the climate: it moves carbon from the slow cycle into the fast one.',
        ),
    ),
    # ── Language & Writing ───────────────────────────────────────────────────
    dict(
        title="Building a Clear Paragraph", subject="Writing", category="Language Arts",
        tags=["composition", "structure", "rhetoric"], level="Introductory", minutes=5,
        outline="## Building a Clear Paragraph\n\nA clear paragraph develops one idea, stated up front and supported by evidence, so a reader can follow the argument without rereading.\n\n"
        + brief(
            "Topic sentence, then support, then a link back or forward: unity and coherence do the work.",
            ["One paragraph carries one controlling idea",
             "The topic sentence names that idea, usually first",
             "Evidence and explanation alternate — claim, proof, reasoning",
             "Transitions signal how each sentence relates to the last"],
            ["State the single point the paragraph will make",
             "Give the strongest piece of evidence for it",
             "Explain how that evidence supports the point",
             "Add a second example or address an objection",
             "Close by linking to the thesis or the next paragraph"],
            "Weak: five loosely related sentences about a novel's setting, mood and characters. Strong: a topic sentence claiming the setting mirrors the protagonist's isolation, then two quoted details, each followed by a sentence explaining the effect.",
            ["Starting with background and burying the point in the middle",
             "Listing evidence without explaining what it shows",
             "Letting one paragraph drift across two or three ideas"],
            "Say the point first, prove it, explain the proof, then connect — one idea per paragraph.",
            matters='Clear paragraphs are the unit of every essay, report and email, and fixing them is the fastest way to write more persuasively.',
        ),
    ),
    # ── Art & Music ──────────────────────────────────────────────────────────
    dict(
        title="Colour Theory Basics", subject="Design", category="Arts",
        tags=["colour", "visual design", "composition"], level="Introductory", minutes=5,
        outline="## Colour Theory Basics\n\nColour theory is the set of guidelines for mixing colours and combining them so a composition feels intentional rather than accidental.\n\n"
        + brief(
            "The colour wheel organises hue; value and saturation do most of the perceptual work; a few standard schemes cover most needs.",
            ["Hue is the colour name, value is lightness, saturation is intensity",
             "Complementary colours sit opposite and create maximum contrast",
             "Analogous colours sit adjacent and feel harmonious",
             "Warm colours advance, cool colours recede"],
            ["Choose a dominant hue that sets the mood",
             "Pick a scheme: complementary, analogous, triadic or monochromatic",
             "Set a value structure first — where is the lightest and darkest point",
             "Use saturation sparingly; let one area be the most vivid",
             "Test in greyscale to check the composition still reads"],
            "A poster uses a deep blue background (cool, recedes) with a single high-saturation orange headline (its complement). The eye jumps straight to the text because it is the only warm, vivid element against a calm field.",
            ["Using many fully saturated colours at once, so nothing stands out",
             "Ignoring value — a design can fail in greyscale even with 'nice' colours",
             "Treating the colour wheel as rules rather than starting points"],
            "Pick one dominant hue, control value and saturation, and let a single accent do the shouting.",
            matters='It is the difference between a design that looks intentional and one that looks accidental, and it takes only a few rules.',
        ),
    ),
]


# ─────────────────────────────────────────────────────────────────────────────
# Index tier — broad browsable titles across subjects (no pre-built deck).
# ─────────────────────────────────────────────────────────────────────────────

INDEX: dict[str, dict] = {
    "Biology": dict(category="Science", topics=[
        "Cell Structure and Organelles", "Mitosis and Meiosis", "Enzymes and Activation Energy",
        "Cellular Respiration", "The Cell Membrane and Transport", "Mendelian Genetics",
        "Protein Synthesis", "The Human Immune System", "The Nervous System", "The Endocrine System",
        "The Circulatory System", "The Respiratory System", "The Digestive System", "Homeostasis",
        "Ecosystems and Energy Flow", "Population Ecology", "The Nitrogen Cycle", "Biodiversity and Conservation",
        "Bacteria and Archaea", "Viruses and Their Life Cycles", "Fungi", "Plant Tissues and Growth",
        "Photoperiodism and Plant Hormones", "Animal Behaviour", "Evolutionary Evidence",
        "Speciation", "Phylogenetics and Cladograms", "The Origin of Life", "Stem Cells",
        "CRISPR and Gene Editing", "Cancer Biology", "Antibiotic Resistance", "The Microbiome",
        "Epigenetics", "Biotechnology and Fermentation", "Blood Types and Transfusion",
        "The Kidney and Osmoregulation", "Muscle Contraction", "Vision and the Eye", "Hearing and the Ear",
    ]),
    "Chemistry": dict(category="Science", topics=[
        "Atomic Structure", "Isotopes and Radioactive Decay", "Electron Configuration",
        "Ionic Bonding", "Covalent Bonding", "Metallic Bonding", "Intermolecular Forces",
        "The Mole and Stoichiometry", "Balancing Chemical Equations", "Limiting Reagents",
        "Gas Laws", "Thermochemistry and Enthalpy", "Entropy and Free Energy", "Chemical Kinetics",
        "Chemical Equilibrium", "Le Chatelier's Principle", "Redox Reactions", "Electrochemical Cells",
        "Electrolysis", "Organic Functional Groups", "Alkanes, Alkenes and Alkynes", "Isomerism",
        "Polymers and Plastics", "Reaction Mechanisms", "Catalysis", "Spectroscopy Basics",
        "Chromatography", "Titration Curves", "Buffers and Buffer Capacity", "Solubility and Ksp",
        "Colligative Properties", "Coordination Compounds", "The d-Block Elements", "Nuclear Chemistry",
        "Green Chemistry", "The Chemistry of Water", "Acid Rain", "Batteries and Fuel Cells",
    ]),
    "Physics": dict(category="Science", topics=[
        "Kinematics in One Dimension", "Projectile Motion", "Circular Motion and Centripetal Force",
        "Work, Energy and Power", "Conservation of Momentum", "Rotational Dynamics", "Simple Harmonic Motion",
        "Gravitation and Orbits", "Fluid Statics and Buoyancy", "Bernoulli's Principle",
        "Temperature and Heat Transfer", "The Ideal Gas Law", "The Laws of Thermodynamics",
        "Heat Engines and Efficiency", "Waves and Wave Properties", "Sound and the Doppler Effect",
        "Reflection and Refraction", "Lenses and Mirrors", "Interference and Diffraction",
        "Electric Fields and Potential", "Capacitors", "Magnetic Fields and Forces",
        "Electromagnetic Induction", "Alternating Current", "Electromagnetic Waves",
        "The Photoelectric Effect", "Atomic Spectra and the Bohr Model", "Nuclear Fission and Fusion",
        "Special Relativity", "Quantum Tunnelling", "Semiconductors and Diodes", "Superconductivity",
    ]),
    "Mathematics": dict(category="Math", topics=[
        "Functions and Their Graphs", "Limits and Continuity", "The Fundamental Theorem of Calculus",
        "Techniques of Integration", "Sequences and Series", "Taylor and Maclaurin Series",
        "Differential Equations", "Vectors and Dot Products", "Matrices and Determinants",
        "Eigenvalues and Eigenvectors", "Systems of Linear Equations", "Complex Numbers",
        "Mathematical Induction", "Combinatorics and Counting", "Probability Distributions",
        "The Normal Distribution", "Hypothesis Testing", "Confidence Intervals", "Linear Regression",
        "Trigonometric Identities", "The Law of Sines and Cosines", "Conic Sections", "Polar Coordinates",
        "Logarithms and Exponentials", "Set Theory Basics", "Logic and Truth Tables", "Graph Theory Basics",
        "Modular Arithmetic", "The Pythagorean Theorem", "Geometric Transformations", "Vectors in 3D",
        "Optimisation with Derivatives", "Related Rates", "Numerical Methods",
    ]),
    "Computer Science": dict(category="Technology", topics=[
        "Arrays and Linked Lists", "Stacks and Queues", "Hash Tables", "Binary Search Trees",
        "Heaps and Priority Queues", "Graphs and Graph Representations", "Breadth-First Search",
        "Depth-First Search", "Dijkstra's Shortest Path", "Dynamic Programming", "Greedy Algorithms",
        "Divide and Conquer", "Sorting Algorithms Compared", "Binary Search", "Recursion and the Call Stack",
        "Time and Space Complexity", "Object-Oriented Programming", "Design Patterns", "SOLID Principles",
        "Relational Databases and SQL", "Database Normalisation", "Indexing and Query Plans",
        "The TCP/IP Model", "DNS Resolution", "REST API Design", "Caching Strategies", "Concurrency and Threads",
        "Deadlocks and Race Conditions", "Operating System Scheduling", "Virtual Memory and Paging",
        "Version Control with Git", "Compilers and Interpreters", "Regular Expressions", "Finite Automata",
        "Public-Key Cryptography", "Hashing and Digital Signatures", "Machine Learning Basics",
        "Neural Networks and Backpropagation", "Overfitting and Regularisation", "Gradient Descent",
        "Containers and Virtualisation", "CI/CD Pipelines", "Load Balancing", "Message Queues",
    ]),
    "History": dict(category="Humanities", topics=[
        "Ancient Mesopotamia", "Ancient Egypt", "Classical Greece", "The Roman Republic",
        "The Roman Empire", "The Fall of Rome", "The Byzantine Empire", "The Islamic Golden Age",
        "The Medieval Feudal System", "The Crusades", "The Black Death", "The Mongol Empire",
        "The Renaissance", "The Age of Exploration", "The Protestant Reformation", "The Scientific Revolution",
        "The Atlantic Slave Trade", "The Enlightenment", "The American Revolution", "The French Revolution",
        "The Napoleonic Wars", "The Unification of Germany", "The Meiji Restoration", "The Scramble for Africa",
        "World War I: Causes", "The Russian Revolution", "The Great Depression", "The Rise of Fascism",
        "World War II: The Pacific Theatre", "The Holocaust", "Decolonisation After 1945",
        "The Civil Rights Movement", "The Cuban Missile Crisis", "The Fall of the Berlin Wall",
        "Apartheid in South Africa", "The Space Race",
    ]),
    "Economics": dict(category="Business", topics=[
        "Opportunity Cost and Trade-offs", "Elasticity of Demand", "Consumer and Producer Surplus",
        "Market Failure and Externalities", "Public Goods and the Free-Rider Problem", "Monopoly and Market Power",
        "Oligopoly and Game Theory", "Perfect Competition", "Labour Markets and Wages",
        "GDP and How It Is Measured", "Inflation and the CPI", "Unemployment Types",
        "Fiscal Policy", "Monetary Policy and Central Banks", "The Money Supply and Banking",
        "Interest Rates and the Yield Curve", "Exchange Rates", "Comparative Advantage and Trade",
        "Tariffs and Trade Barriers", "Economic Growth and Productivity", "Income Inequality and the Gini Coefficient",
        "Behavioural Economics", "The Business Cycle", "Taxation and Deadweight Loss",
    ]),
    "Finance": dict(category="Business", topics=[
        "Time Value of Money", "Net Present Value and IRR", "Risk and Return", "Diversification and Portfolio Theory",
        "The Capital Asset Pricing Model", "Bonds and Yield to Maturity", "Stock Valuation Models",
        "Reading an Income Statement", "Reading a Balance Sheet", "Cash Flow Statements", "Financial Ratios",
        "Working Capital Management", "Capital Budgeting", "The Cost of Capital", "Leverage and Capital Structure",
        "Options and Derivatives Basics", "Efficient Market Hypothesis", "Behavioural Finance and Bias",
        "Personal Budgeting", "Credit Scores and Debt", "Retirement Accounts and Tax Shelters", "Insurance Fundamentals",
    ]),
    "Psychology": dict(category="Social Science", topics=[
        "The Scientific Method in Psychology", "Neurons and Synaptic Transmission", "The Divided Brain",
        "Sensation versus Perception", "Attention and the Cocktail Party Effect", "Memory Systems and Encoding",
        "Forgetting and Retrieval Failure", "Piaget's Stages of Cognitive Development", "Attachment Theory",
        "Erikson's Psychosocial Stages", "Intelligence and IQ Testing", "Motivation and Maslow's Hierarchy",
        "Emotion Theories", "Stress and the General Adaptation Syndrome", "The Big Five Personality Traits",
        "Cognitive Dissonance", "Conformity and the Asch Experiments", "Obedience and Milgram",
        "The Bystander Effect", "Prejudice and Stereotyping", "Heuristics and Cognitive Biases",
        "Major Depressive Disorder", "Anxiety Disorders", "Schizophrenia", "Cognitive Behavioural Therapy",
        "Sleep Stages and Dreaming", "Classical Test Anxiety and Performance",
    ]),
    "Environmental Science": dict(category="Science", topics=[
        "The Greenhouse Effect", "The Water Cycle", "The Phosphorus Cycle", "The Rock Cycle",
        "Plate Tectonics", "Earthquakes and Seismic Waves", "Volcanoes and Magma", "Weather versus Climate",
        "Ocean Currents and the Thermohaline Circulation", "El Niño and La Niña", "Soil Formation and Horizons",
        "Eutrophication", "Ocean Acidification", "The Ozone Layer", "Renewable Energy Sources",
        "Nuclear Power Trade-offs", "Sustainable Agriculture", "Deforestation and Land Use",
        "Freshwater Scarcity", "Plastic Pollution and Microplastics", "Ecological Succession",
        "Keystone Species and Trophic Cascades", "Invasive Species", "Carbon Capture and Storage",
        "Climate Feedback Loops", "The IPCC and Climate Modelling",
    ]),
    "Writing": dict(category="Language Arts", topics=[
        "Thesis Statements", "Structuring an Argumentative Essay", "Introductions That Work",
        "Writing Strong Conclusions", "Using Evidence and Citation", "Avoiding Plagiarism",
        "Active versus Passive Voice", "Sentence Variety and Rhythm", "Common Comma Errors",
        "Parallel Structure", "Concision and Cutting Filler", "Tone and Register", "Transitions and Signposting",
        "Summarising and Paraphrasing", "Peer Review and Revision", "Rhetorical Appeals: Ethos, Pathos, Logos",
        "Logical Fallacies", "Narrative Structure and Story Arc", "Show, Don't Tell", "Writing a Literature Review",
        "The Research Question", "Formatting in APA Style", "Writing Clear Emails", "Technical Documentation Basics",
    ]),
    "Design": dict(category="Arts", topics=[
        "Visual Hierarchy", "The Grid System", "Typography Fundamentals", "Choosing and Pairing Typefaces",
        "White Space and Breathing Room", "Gestalt Principles of Perception", "Contrast, Repetition, Alignment, Proximity",
        "Designing for Accessibility", "Colour Contrast and WCAG", "Wireframing and Prototyping",
        "Design Systems and Component Libraries", "Responsive Layout Principles", "Iconography and Visual Language",
        "Data Visualisation Best Practices", "Choosing the Right Chart", "Motion and Micro-interactions",
        "User Research Methods", "Usability Heuristics", "Information Architecture", "Design Critique",
        "Figure–Ground Relationships",
        "Modular Scale and Vertical Rhythm",
        "Designing Data Tables",
        "Form Design and Input Patterns",
        "Empty States and Onboarding",
        "Error Prevention and Recovery",
        "Dark Mode and Theming",
        "Designing for Touch versus Pointer",
        "Progressive Disclosure",
        "Card Sorting and Tree Testing",
        "Design Tokens",
        "Print versus Screen Layout",
    ]),
    "Philosophy": dict(category="Humanities", topics=[
        "What Is an Argument?", "Deductive versus Inductive Reasoning", "Common Logical Fallacies",
        "The Problem of Induction", "Plato's Theory of Forms", "Aristotle's Virtue Ethics", "Stoicism",
        "Descartes and Radical Doubt", "Empiricism versus Rationalism", "Hume on Causation",
        "Kant's Categorical Imperative", "Utilitarianism", "The Trolley Problem", "Social Contract Theory",
        "Existentialism", "The Mind–Body Problem", "Free Will and Determinism", "The Ship of Theseus",
        "The Problem of Evil", "Epistemic Justification", "Moral Relativism", "Rawls and the Veil of Ignorance",
    ]),
    "Health & Medicine": dict(category="Science", topics=[
        "How Vaccines Train Immunity", "The Cardiac Cycle", "Blood Pressure and Its Regulation",
        "Type 1 versus Type 2 Diabetes", "Cholesterol and Cardiovascular Risk", "The Stress Response and Cortisol",
        "Nutrition: Macronutrients", "Nutrition: Vitamins and Minerals", "The Gut–Brain Axis",
        "Antibiotics: How They Work and Why Resistance Spreads", "Pain Pathways and Analgesics",
        "How Anaesthesia Works", "The Sleep–Wake Cycle and Circadian Rhythm", "BMI and Its Limitations",
        "Inflammation: Acute versus Chronic", "How mRNA Vaccines Work", "The Kidney and Dialysis",
        "Hearing Loss and Prevention", "Reading a Nutrition Label", "Epidemiology: Incidence versus Prevalence",
        "The Lymphatic System",
        "Wound Healing Stages",
        "How Fever Works",
        "Allergies and Anaphylaxis",
        "Autoimmune Disease Basics",
        "The Liver and Detoxification",
        "Bone Remodelling and Osteoporosis",
        "Vision Correction and Refractive Errors",
        "The Placebo Effect",
        "Herd Immunity Thresholds",
        "Screening Tests: Sensitivity and Specificity",
        "Antivirals versus Antibiotics",
        "Blood Glucose Regulation",
        "Hormonal Feedback Loops",
    ]),
    "Astronomy": dict(category="Science", topics=[
        "The Scale of the Solar System", "Kepler's Laws of Planetary Motion", "Why Seasons Happen",
        "Phases of the Moon", "Solar and Lunar Eclipses", "The Life Cycle of a Star", "Stellar Nucleosynthesis",
        "Black Holes and Event Horizons", "The Hertzsprung–Russell Diagram", "Types of Galaxies",
        "The Big Bang and Cosmic Microwave Background", "Dark Matter and Dark Energy", "Exoplanet Detection Methods",
        "The Habitable Zone", "Comets, Asteroids and Meteors", "The Sun's Structure and Activity",
        "Redshift and the Expanding Universe", "Telescopes: Optical to Radio", "Spacecraft Trajectories and Gravity Assists",
        "The Search for Extraterrestrial Life",
        "The Doppler Effect in Astronomy",
        "Parallax and the Cosmic Distance Ladder",
        "Neutron Stars and Pulsars",
        "White Dwarfs and Type Ia Supernovae",
        "The Kuiper Belt and Oort Cloud",
        "Planetary Atmospheres Compared",
        "Tides and the Earth–Moon System",
        "Star Clusters: Open and Globular",
        "Cosmic Rays",
        "Gravitational Waves and LIGO",
        "The Fermi Paradox",
        "Auroras and the Magnetosphere",
    ]),
    "Political Science": dict(category="Social Science", topics=[
        "Forms of Government Compared", "Separation of Powers", "Federalism versus Unitary States",
        "Electoral Systems: FPTP versus Proportional", "How a Bill Becomes Law", "Judicial Review",
        "Civil Liberties versus Civil Rights", "Political Ideologies on a Spectrum", "Interest Groups and Lobbying",
        "Public Opinion and Polling", "The Media and Political Agenda-Setting", "International Relations Theories",
        "The United Nations System", "Sovereignty and Intervention", "Nationalism", "Democratic Backsliding",
        "The Welfare State", "Constitutional Design", "Political Parties and Party Systems", "Voter Turnout and Participation",
        "Gerrymandering and Redistricting",
        "Coalition Government Formation",
        "The Median Voter Theorem",
        "Populism: Definitions and Debates",
        "Authoritarianism versus Totalitarianism",
        "Civil–Military Relations",
        "Federal Fiscal Transfers",
        "Referendums and Direct Democracy",
        "Political Socialisation",
        "Comparative Constitutional Courts",
        "Foreign Aid and Conditionality",
        "Deterrence and Coercion in IR",
    ]),
    "Linguistics": dict(category="Humanities", topics=[
        "Phonetics: How Speech Sounds Are Made", "Phonology and Phonemes", "Morphology: Word Building",
        "Syntax and Phrase Structure", "Semantics versus Pragmatics", "Language Acquisition in Children",
        "The Critical Period Hypothesis", "Language Change Over Time", "Dialects and Sociolinguistics",
        "Writing Systems of the World", "Bilingualism and Code-Switching", "The International Phonetic Alphabet",
        "Historical Reconstruction and Language Families", "Sign Languages as Full Languages", "Pidgins and Creoles",
        "The Sapir–Whorf Hypothesis",
        "Prosody and Intonation",
        "Assimilation and Elision",
        "Derivational versus Inflectional Morphology",
        "Ambiguity and Parsing",
        "Deixis and Reference",
        "Speech Acts",
        "Politeness Theory",
        "Corpus Linguistics",
        "Language and the Brain: Aphasia",
        "Second Language Acquisition",
        "Orthographic Depth",
        "Endangered Languages and Revitalisation",
    ]),
    "Statistics & Data": dict(category="Math", topics=[
        "Descriptive versus Inferential Statistics", "Measures of Central Tendency", "Variance and Standard Deviation",
        "Sampling Methods and Bias", "The Central Limit Theorem", "Standard Error and Margin of Error",
        "p-values and Statistical Significance", "Type I and Type II Errors", "Statistical Power",
        "Correlation versus Causation", "Simpson's Paradox", "Chi-Square Tests", "t-Tests and ANOVA",
        "Multiple Regression", "Logistic Regression", "Confidence versus Prediction Intervals",
        "Bootstrapping and Resampling", "Bayesian versus Frequentist Inference", "Time Series Decomposition",
        "A/B Testing Design", "Survivorship Bias", "Data Cleaning and Missing Values", "Exploratory Data Analysis",
        "Feature Engineering", "Dimensionality Reduction with PCA", "Clustering with k-Means", "Decision Trees",
        "Random Forests and Boosting", "Cross-Validation", "The Bias–Variance Tradeoff", "Data Ethics and Privacy",
        "Reading and Misreading Graphs",
    ]),
    "Geography": dict(category="Social Science", topics=[
        "Map Projections and Their Distortions", "Latitude, Longitude and Time Zones", "Biomes of the World",
        "The Köppen Climate Classification", "Rivers and Drainage Basins", "Coastal Processes and Landforms",
        "Glaciation and Glacial Landforms", "Deserts and Desertification", "Urbanisation and Megacities",
        "Population Pyramids and Demographic Transition", "Migration: Push and Pull Factors", "Globalisation and Trade Networks",
        "Natural Hazards and Risk", "Food Security and Famine", "Water Resources and Transboundary Rivers",
        "Resource Extraction and Development", "Tourism and Its Impacts", "GIS and Remote Sensing",
        "Land Use and Zoning", "Cultural Landscapes",
        "Plate Boundaries and Continental Drift",
        "Tropical Rainforest Ecosystems",
        "Savanna and Grassland Dynamics",
        "Mediterranean Climates",
        "Mountain Weather and Orographic Rain",
        "Karst and Cave Systems",
        "Delta Formation",
        "Soil Erosion and Conservation",
        "Spatial Inequality Within Cities",
        "Gentrification",
        "Transport Geography and Accessibility",
        "Borders and Territorial Disputes",
    ]),
    "Sociology & Anthropology": dict(category="Social Science", topics=[
        "The Sociological Imagination", "Culture, Norms and Values", "Socialisation and the Self",
        "Social Stratification and Class", "Race and Ethnicity as Social Constructs", "Gender and Society",
        "Family Structures Across Cultures", "Religion and Secularisation", "Education and Social Reproduction",
        "Deviance and Social Control", "Bureaucracy and Organisations", "Social Movements",
        "Urban Communities and Networks", "Globalisation and Local Culture", "Kinship Systems",
        "Rituals and Rites of Passage", "Language and Cultural Identity", "Ethnographic Fieldwork Methods",
        "Cultural Relativism versus Ethnocentrism", "The Origins of Agriculture",
        "Symbolic Interactionism",
        "Functionalism versus Conflict Theory",
        "Social Capital and Networks",
        "Institutions and Path Dependence",
        "Moral Panics",
        "The Digital Divide",
        "Gift Economies",
        "Totemism and Taboo",
        "Ethnicity and Nationalism",
        "Ageing and the Life Course",
        "Work, Automation and Precarity",
        "Consumer Culture",
    ]),
    "Business & Management": dict(category="Business", topics=[
        "SWOT Analysis", "Porter's Five Forces", "The Business Model Canvas", "Value Chain Analysis",
        "Product Life Cycle", "The Marketing Mix (4 Ps)", "Market Segmentation and Targeting", "Brand Positioning",
        "Pricing Strategies", "The Sales Funnel", "Customer Lifetime Value", "Net Promoter Score",
        "Lean Startup and MVPs", "Agile and Scrum", "Kanban and Flow", "OKRs and Goal Setting",
        "Organisational Structures", "Leadership Styles", "Motivation Theories at Work", "Change Management",
        "Negotiation Fundamentals", "Supply Chain Management", "Inventory and Just-in-Time", "Quality Management and Six Sigma",
        "Project Scope and the Iron Triangle", "Risk Management", "Corporate Governance", "Business Ethics and CSR",
        "Mergers and Acquisitions", "Competitive Strategy: Cost versus Differentiation",
    ]),
    "Law": dict(category="Social Science", topics=[
        "Common Law versus Civil Law Systems", "The Structure of a Court System", "Precedent and Stare Decisis",
        "Elements of a Contract", "Breach of Contract and Remedies", "Tort Law: Negligence",
        "Criminal Law: Mens Rea and Actus Reus", "Burden and Standard of Proof", "Constitutional Rights",
        "Due Process", "Intellectual Property: Patents, Trademarks, Copyright", "Employment Law Basics",
        "Property Law: Ownership and Possession", "Administrative Law and Regulation", "International Law and Treaties",
        "Alternative Dispute Resolution", "Evidence and Admissibility", "Legal Reasoning and IRAC",
        "Data Protection and Privacy Law", "Company Formation and Liability",
        "Statutory Interpretation",
        "Judicial Independence",
        "Jurisdiction and Venue",
        "Class Action Lawsuits",
        "Defamation: Libel and Slander",
        "Strict Liability",
        "Contract Formation: Offer and Acceptance",
        "Consideration and Promissory Estoppel",
        "Criminal Defences",
        "Sentencing Principles",
        "Human Rights Instruments",
        "Competition and Antitrust Law",
    ]),
    "Music & Performing Arts": dict(category="Arts", topics=[
        "Reading Standard Notation", "Rhythm, Metre and Time Signatures", "Major and Minor Scales",
        "Intervals and Ear Training", "Triads and Seventh Chords", "Chord Progressions and Cadences",
        "Keys and the Circle of Fifths", "Modes of the Major Scale", "Song Form and Structure",
        "Counterpoint Basics", "Orchestration and Instrument Families", "Dynamics and Articulation",
        "The Overtone Series", "Tuning Systems and Temperament", "Music of the Baroque Era",
        "The Classical Style", "Romanticism in Music", "Jazz Harmony and Improvisation", "Twentieth-Century Techniques",
        "Film Scoring and Leitmotif", "Acoustics of Performance Spaces", "Stagecraft and Blocking",
    ]),
    "Literature": dict(category="Language Arts", topics=[
        "Elements of Fiction", "Point of View and Narration", "Character and Characterisation",
        "Plot Structure and Conflict", "Setting and Atmosphere", "Theme versus Motif", "Figurative Language",
        "Meter and Scansion in Poetry", "Forms of Poetry: Sonnet to Free Verse", "Dramatic Structure and Tragedy",
        "The Epic Tradition", "Realism and Naturalism", "Modernism in Literature", "Postmodern Techniques",
        "Close Reading Methods", "Literary Theory: A Survey", "The Bildungsroman", "Satire and Irony",
        "Unreliable Narrators", "Adaptation: Page to Screen", "The Short Story Form", "Writing About Literature",
    ]),
    "Engineering": dict(category="Technology", topics=[
        "Free-Body Diagrams and Statics", "Stress, Strain and Young's Modulus", "Beams and Bending Moments",
        "Trusses and Method of Joints", "Factor of Safety", "Fluid Mechanics: Laminar and Turbulent Flow",
        "Heat Transfer: Conduction, Convection, Radiation", "Thermodynamic Cycles", "Control Systems and Feedback",
        "PID Controllers", "Signals and the Fourier Transform", "Op-Amp Circuits", "Logic Gates and Boolean Algebra",
        "Digital-to-Analog Conversion", "Materials Selection", "Fatigue and Failure Analysis", "CAD and Tolerancing",
        "Manufacturing Processes Overview", "Finite Element Analysis Concepts", "Engineering Design Process",
        "Reliability and Redundancy", "Systems Engineering and Requirements",
    ]),
    "Cybersecurity": dict(category="Technology", topics=[
        "The CIA Triad", "Threat Modelling", "Common Web Vulnerabilities (OWASP Top 10)", "SQL Injection",
        "Cross-Site Scripting", "Authentication versus Authorization", "Multi-Factor Authentication",
        "Password Hashing and Salting", "Symmetric versus Asymmetric Encryption", "TLS and Certificate Chains",
        "Public Key Infrastructure", "Social Engineering and Phishing", "Malware Types", "Network Firewalls and Segmentation",
        "Intrusion Detection Systems", "Zero Trust Architecture", "Security Logging and SIEM", "Incident Response Lifecycle",
        "Penetration Testing Phases", "Secure Software Development Lifecycle", "Supply Chain Security", "Ransomware and Backups",
    ]),
    "Art History": dict(category="Arts", topics=[
        "Cave Painting and Prehistoric Art", "Egyptian Art and Convention", "Greek Sculpture and the Classical Ideal",
        "Roman Art and Portraiture", "Byzantine Mosaics and Icons", "Romanesque and Gothic Architecture",
        "The Early Italian Renaissance", "Linear Perspective", "The High Renaissance", "The Northern Renaissance",
        "Baroque Drama and Light", "Rococo", "Neoclassicism", "Romantic Painting", "Realism in the 19th Century",
        "Impressionism", "Post-Impressionism", "Cubism", "Surrealism", "Abstract Expressionism", "Pop Art",
        "Conceptual and Installation Art",
    ]),
    "Geology": dict(category="Science", topics=[
        "Minerals and Their Properties", "The Three Rock Types", "Bowen's Reaction Series", "Relative and Absolute Dating",
        "The Geologic Time Scale", "Stratigraphy and the Law of Superposition", "Plate Boundaries in Detail",
        "Mountain Building (Orogeny)", "Faults and Folds", "Volcano Types and Eruption Styles", "Weathering and Erosion",
        "Sedimentary Environments", "Groundwater and Aquifers", "Karst Landscapes", "Mass Wasting and Landslides",
        "Fossils and Fossilisation", "Ice Ages and Milankovitch Cycles", "Economic Geology and Ore Deposits",
        "Reading a Geologic Map", "Earth's Internal Structure",
        "Igneous Textures and Cooling Rates",
        "Metamorphic Grade and Index Minerals",
        "Cross-Cutting Relationships",
        "Unconformities in the Rock Record",
        "Seismic Tomography of the Mantle",
        "Isostasy",
        "Continental Rifting",
        "Ophiolites and Ancient Oceans",
        "Mineral Cleavage and Fracture",
        "Geothermal Energy Systems",
        "Landslide Hazard Mapping",
        "Coastal Erosion Management",
    ]),
    "Nutrition & Food Science": dict(category="Science", topics=[
        "Energy Balance and Metabolism", "Carbohydrates and Glycaemic Response", "Dietary Fats and Fatty Acids",
        "Protein Quality and Amino Acids", "Fibre and Digestive Health", "Water and Electrolyte Balance",
        "The Glycaemic Index in Practice", "Food Labelling and Serving Sizes", "Food Preservation Methods",
        "Fermentation in Food", "The Maillard Reaction", "Emulsions and Foams in Cooking", "Food Safety and the Danger Zone",
        "Foodborne Pathogens", "Dietary Patterns Compared", "Nutrient Density versus Energy Density",
        "Supplements: Evidence and Hype", "Reading Nutrition Research Critically", "Sugar and Sweeteners",
        "Salt, Blood Pressure and Processed Food",
        "Digestion and Nutrient Absorption",
        "Glycogen and Endurance",
        "Protein Timing Myths",
        "Hydration and Athletic Performance",
        "Food Allergens and Cross-Contact",
        "Rancidity and Antioxidants",
        "Gelatinisation of Starch",
        "Leavening Agents",
        "pH and Food Preservation",
        "Umami and Flavour Perception",
        "Meal Planning on a Budget",
        "Interpreting Observational Diet Studies",
    ]),
    "Earth & Climate Systems": dict(category="Science", topics=[
        "Radiative Forcing Explained", "The Global Energy Budget", "Albedo and Surface Feedbacks",
        "Carbon Budgets and Net Zero", "Sea Level Rise: Causes and Projections", "Extreme Weather Attribution",
        "The Jet Stream and Mid-Latitude Weather", "Monsoon Systems", "Tropical Cyclone Formation", "Drought Indices",
        "Permafrost and the Carbon Feedback", "Coral Bleaching", "Climate Tipping Points", "Aerosols and Cooling",
        "Paleoclimate Proxies", "Downscaling Climate Models", "Adaptation versus Mitigation", "Climate Finance",
        "Geoengineering Proposals", "The Water–Energy–Food Nexus",
        "Cloud Types and Formation",
        "The Coriolis Effect",
        "Atmospheric Stability and Inversions",
        "Snow and Ice Albedo Feedback",
        "Ocean Heat Content",
        "Thermohaline Slowdown Risk",
        "Wildfire Weather and Fuel Moisture",
        "Urban Heat Islands",
        "Air Quality and PM2.5",
        "Stratospheric Ozone Recovery",
        "Carbon Isotopes as Fingerprints",
        "Attribution of Sea Ice Loss",
    ]),
    "Machine Learning & AI": dict(category="Technology", topics=[
        "Supervised versus Unsupervised Learning", "Train, Validation and Test Splits", "Loss Functions Explained",
        "Linear and Logistic Regression as ML", "k-Nearest Neighbours", "Support Vector Machines", "Naive Bayes Classifiers",
        "Decision Trees and Information Gain", "Ensemble Methods: Bagging and Boosting", "Gradient Descent Variants",
        "Backpropagation Step by Step", "Activation Functions", "Convolutional Neural Networks", "Recurrent Networks and LSTMs",
        "Attention and Transformers", "Word Embeddings", "Large Language Models: How They Are Trained", "Tokenisation",
        "Fine-Tuning versus Prompting", "Retrieval-Augmented Generation", "Overfitting, Regularisation and Dropout",
        "Batch Normalisation", "Hyperparameter Tuning", "Evaluation Metrics: Precision, Recall, F1, ROC", "Confusion Matrices",
        "Class Imbalance Strategies", "Reinforcement Learning Basics", "Q-Learning", "Policy Gradients",
        "Generative Adversarial Networks", "Diffusion Models", "Model Interpretability and SHAP", "Bias and Fairness in ML",
        "Data Leakage in Practice", "MLOps and Model Deployment", "Vector Databases and Similarity Search",
    ]),
    "World Religions & Mythology": dict(category="Humanities", topics=[
        "Hinduism: Core Concepts", "Buddhism: The Four Noble Truths", "Jainism and Ahimsa", "Sikhism: History and Beliefs",
        "Judaism: Torah and Covenant", "Christianity: Origins and Branches", "Islam: The Five Pillars", "Daoism and Wu Wei",
        "Confucianism as Ethical System", "Shinto and Kami", "Zoroastrianism", "Indigenous Belief Systems",
        "Greek Mythology: The Olympians", "Norse Mythology and Ragnarök", "Egyptian Mythology and the Afterlife",
        "Comparative Creation Myths", "Pilgrimage Across Traditions", "Sacred Texts and Interpretation",
        "Secular Humanism", "Ritual and Symbol in Religion",
    ]),
    "Communication & Public Speaking": dict(category="Language Arts", topics=[
        "Structuring a Persuasive Speech", "Managing Speaking Anxiety", "Vocal Delivery and Pacing",
        "Body Language and Stage Presence", "Designing Slides That Support, Not Distract", "Storytelling for Impact",
        "Opening Hooks and Strong Closes", "Handling Q&A", "Adapting to Your Audience", "The Elevator Pitch",
        "Active Listening", "Giving and Receiving Feedback", "Difficult Conversations", "Cross-Cultural Communication",
        "Nonverbal Communication", "Persuasion and Influence Principles", "Facilitating a Meeting", "Debate Fundamentals",
        "Writing for the Ear versus the Page", "Impromptu Speaking Frameworks",
    ]),
    "Personal Development & Study Skills": dict(category="Social Science", topics=[
        "Spaced Repetition and the Forgetting Curve", "Active Recall as a Study Method", "The Feynman Technique",
        "Interleaving versus Blocked Practice", "Note-Taking Systems Compared", "The Pomodoro Technique and Deep Work",
        "Goal Setting with SMART and OKRs", "Habit Formation and Cue–Routine–Reward", "Growth versus Fixed Mindset",
        "Managing Procrastination", "Prioritisation with the Eisenhower Matrix", "Time Blocking",
        "Reading Strategies: SQ3R", "Exam Preparation and Practice Testing", "Sleep, Exercise and Cognitive Performance",
        "Attention and Digital Distraction", "Metacognition and Self-Assessment", "Building a Second Brain",
        "Decision-Making Frameworks", "Stress Management Techniques",
    ]),
}


def build() -> list[dict]:
    entries: list[dict] = []
    seen: set[str] = set()

    for c in CURATED:
        slug = slugify(c["title"])
        seen.add(slug)
        entries.append({
            "slug": slug,
            "title": c["title"],
            "subject": c["subject"],
            "category": c["category"],
            "tags": c["tags"],
            "level": c["level"],
            "minutes": c["minutes"],
            "status": "outline",
            "outline": c["outline"],
        })

    for subject, spec in INDEX.items():
        for topic in spec["topics"]:
            slug = slugify(topic)
            if slug in seen:
                continue
            seen.add(slug)
            entries.append({
                "slug": slug,
                "title": topic,
                "subject": subject,
                "category": spec["category"],
                "tags": [subject.lower()],
                "level": "Introductory",
                "minutes": 6,
                "status": "index",
                "outline": "",
            })

    entries.sort(key=lambda e: (e["category"], e["subject"], e["title"]))
    return entries


if __name__ == "__main__":
    data = build()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps({"entries": data}, ensure_ascii=False, indent=1), encoding="utf-8")
    n_outline = sum(1 for e in data if e["status"] == "outline")
    print(f"wrote {OUT}  ({len(data)} entries, {n_outline} with briefs, "
          f"{len(data) - n_outline} index-only)")
    by_subject: dict[str, int] = {}
    for e in data:
        by_subject[e["subject"]] = by_subject.get(e["subject"], 0) + 1
    for s, n in sorted(by_subject.items()):
        print(f"  {s:24} {n}")
